name: "Release version"

on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get release version
        id: release_version
        run: echo ::set-output name=result::${GITHUB_REF/refs\/tags\/v/}
      - name: Print version
        run: echo ${{ steps.release_version.outputs.result }}
