name: "Release version"

on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get release version
        run: | 
          echo "result=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
          echo "major_version=$(cut -d '.' -f 1 <<< $GITHUB_REF_NAME)" >> $GITHUB_ENV
      - name: Print version
        run: echo "${{ env.result }}"
      - name: Print ref
        run: echo "${{ github.ref_name }}"
      - name: Major version
        if: ${{ !contains(github.ref_name, 'alpha') && !contains(github.ref_name, 'beta') }}
        run: echo "${{ env.major_version }}"
