name: "Script"

on:
  workflow_dispatch:


jobs:
  job1: 

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shasum
        run: |
          bash .github/workflows/scripts/test.sh
        env:
          OS: ${{ runner.os }}

      - name: Check jq
        run: |
         jq --version
