name: "Siegfried install"

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
          run: |
            go install github.com/richardlehane/siegfried/cmd/sf@latest
            sf -update