name: "Siegfried install"

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
          check-latest: true
      - name: Install dependencies
        run: |
          go install github.com/richardlehane/siegfried/cmd/sf@latest
          sf -update