name: "Build"

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup PostgreSQL service
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '9.6'
          postgresql user: postgres
      - name: Run Tests
        run: telnet 127.0.0.1 3306
        env:
          DPT_MYSQL_USER: "root"
          DPT_MYSQL_PASS: ""
          DPT_POSTGRESQL_USER: "postgres"
          DPT_POSTGRESQL_PASS: ""