name: "Release"

on:
  push:
    tags:
      - "**"
    branches-ignore:
      - "**"

jobs:
  deploy:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: file
          asset_name: file
          tag: ${{ github.ref }}
          release_name: Version ${{ steps.get_version.outputs.VERSION }}