name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  job1: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ runner.os }}-${{ github.event.inputs.version }}

      - name: Build
        run: |
          mkdir -p dist
          touch dist/file1-${{ runner.os }}
          touch dist/file2-${{ runner.os }}
          echo "aaaaa" > dist/file1-${{ runner.os }}
          echo "bbbbb" > dist/file2-${{ runner.os }}

  job2:
    needs: [job1]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ runner.os }}-${{ github.event.inputs.version }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: Version ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}