name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  job1: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ github.event.inputs.version }}

      - name: Build
        run: |
          mkdir -p dist
          touch dist/file1-${{ runner.os }}
          touch dist/file2--${{ runner.os }}

  job2:
    needs: [job1]
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ github.event.inputs.version }}
      
      - name: List directories
        run: ls dist