name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  job1: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ runner.os }}-${{ github.event.inputs.version }}

      - name: Build
        run: |
          mkdir -p dist
          touch dist/file1-${{ runner.os }}
          touch dist/file2-${{ runner.os }}
          echo "aaaaa" > dist/file1-${{ runner.os }}
          echo "bbbbb" > dist/file2-${{ runner.os }}
          

      - name: Set GitHub config
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          git config --local user.email "hmtlguimaraes@gmail.com"
          git config --local user.name "Miguel Guimarães"
      
      - name: Run release script
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "Version $TAG" > version
          git add -u
          git commit -m "Setting version $RELEASE_VERSION"
        env:
          TAG: ${{ github.event.inputs.version }}
      
      - name: Push changes
        if: startsWith(matrix.os, 'ubuntu')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  job2:
    needs: [job1]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist/*
          key: ${{ runner.os }}-${{ github.event.inputs.version }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: Version ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}