name: "Build"

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Setup PostgreSQL service
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '9.6'
          postgresql password: '123456'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Run Tests
        run: mysql -s --user="$DPT_MYSQL_USER" --password="$DPT_MYSQL_PASS" --host="127.0.0.1" --port="$DPT_MYSQL_PORT" --execute="SELECT VERSION();"
        env:
          DPT_MYSQL_USER: "root"
          DPT_MYSQL_PASS: ""
          DPT_POSTGRESQL_USER: "postgres"
          DPT_POSTGRESQL_PASS: ""
          PGPASSWORD: '123456'
          DPT_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}